#----------------------------------------------------eureka -------------------------------客户端口
server:
  port: 7002


spring:
  application:
    name: api-feign

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    #instance-id: ${spring.application.name}:${server.port}
    #心跳间隔5s，默认30s。每一个服务配置后，心跳间隔和心跳超时时间会被保存在server端，不同服务的心跳频率可能不同，server端会根据保存的配置来分别探活
    lease-renewal-interval-in-seconds: 5
    #心跳超时时间10s，默认90s。从client端最后一次发出心跳后，达到这个时间没有再次发出心跳，表示服务不可用，将它的实例从注册中心移除
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      #注册中心路径，表示我们向这个注册中心注册服务，如果向多个注册中心注册，用“，”进行分隔
      defaultZone: http://localhost:8081/eureka

