#----------------------------------------------------eureka -------------------------------客户端口
server:
  port: 7003

spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    #心跳间隔5s，默认30s。每一个服务配置后，心跳间隔和心跳超时时间会被保存在server端，不同服务的心跳频率可能不同，server端会根据保存的配置来分别探活
    lease-renewal-interval-in-seconds: 5
    #心跳超时时间10s，默认90s。从client端最后一次发出心跳后，达到这个时间没有再次发出心跳，表示服务不可用，将它的实例从注册中心移除
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      #注册中心路径，表示我们向这个注册中心注册服务，如果向多个注册中心注册，用“，”进行分隔
      defaultZone: http://localhost:8081/eureka






#=================================================zuul============================================

zuul:
  ignoredServices: /**/
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    api-feign: /feign/** # 将商品微服务映射到/item/**
#    search-service: /search/** # 将商品微服务映射到/item/**
#    user-service: /user/**
#    auth-service: /auth/**
#    cart-service: /cart/**
#    order-service: /order/**
  add-host-header: true
#  ignored-patterns: /upload/**
#  ignored-services: upload-service
  sensitive-headers:
ribbon:
  ConnectTimeout: 25000 # 连接超时时间(ms)
  ReadTimeout: 20000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

#解释一下：上面这段配置表示，/api-user/开头的url请求，将转发到service-provider这个微服务上，
#/api-order/开头的url请求，将转发到service-consumer这个微服务上。

hystrix:
  command:
    defalut:
      excution:
        isolation:
          thread:
            timeoutInMillseconds: 60000
