#server:
#  port: 8008
#spring:
#  application:
#    name: api-redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        #?????????????????????????????????????????????????????????????????????????0??????????
#        max-idle: 0
#        #?????????????????????????0?????????
#        max-Active: 8
#        #?????????????????????????Åﬁ??????????-1??????????
#        max-Wait: 1ms


